### ISSUE TITLE
multiaddr issue leads to panic

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1275] opened 2018-11-02 19:53 UTC
```
panic: multiaddr failed to convert back to string. corrupted?

goroutine 21769 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr.(*multiaddr).String(0xc4217cab00, 0x5399cd0, 0xc420064948)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr/multiaddr.go:64 +0x84
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*ObservedAddrSet).Add(0xc420064948, 0x5c12b00, 0xc4217cab00, 0x5c12b00, 0xc422a022e0)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify/obsaddr.go:83 +0xa2
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*IDService).consumeObservedAddress(0xc420064900, 0xc420902050, 0x4c, 0x4c, 0x5c13f80, 0xc4214d8180)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify/id.go:411 +0x5d5
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*IDService).consumeMessage(0xc420064900, 0xc424621cb0, 0x5c13f80, 0xc4214d8180)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify/id.go:205 +0x124
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*IDService).ResponseHandler(0xc420064900, 0x5c14a00, 0xc423b02280)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify/id.go:152 +0x351
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*IDService).IdentifyConn(0xc420064900, 0x5c13f80, 0xc4214d8180)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify/id.go:112 +0x85c
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic.(*BasicHost).newConnHandler(0xc420204380, 0x5c13f80, 0xc4214d8180)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic/basic_host.go:227 +0xaf
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic.(*BasicHost).(github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic.newConnHandler)-fm(0x5c13f80, 0xc4214d8180)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic/basic_host.go:174 +0x3e
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm.(*Network).SetConnHandler.func1(0xc4214d8180)
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm/swarm_net.go:160 +0x3b
created by github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm.(*Swarm).SetConnHandler.func2
	/Users/rob/develop/openbazaar/v2/go/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm/swarm.go:260 +0x67
exit status 2
```

**Comment by placer14** [comment] 2018-11-02 20:00
Confirmed. This issue is limited to the `multiwallet` branch.

**Comment by placer14** [comment] 2018-11-03 03:14
Thanks for the report, @ajsingh007. Apologies for the misinformation above.

**Comment by ajsingh007** [comment] 2018-11-05 23:12
Update on my end - I think I am no longer getting this issue as my store has remained up since Saturday Nov. 3rd

**Comment by jlopp** [comment] 2018-11-07 15:59
Our OB instance (v0.12.3) crashed with the same error. I've upgraded to v0.12.4 though I guess I shouldn't expect that to fix it.

```
2018/11/02 15:10:40 http: TLS handshake error from 127.0.0.1:4001: EOF
panic: multiaddr failed to convert back to string. corrupted?

goroutine 234755374 [running]:
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr.(*multiaddr).String(0x
c433862b40, 0x1635c78, 0xc420090c48)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr/
multiaddr.go:64 +0x84
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*O
bservedAddrSet).Add(0xc420090c48, 0x16f96c0, 0xc433862b40, 0x16f96c0, 0xc433863f20)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p
/protocol/identify/obsaddr.go:83 +0xa2
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*I
DService).consumeObservedAddress(0xc420090c00, 0xc42bd305f0, 0x4c, 0x4c, 0x16fc000, 0xc43603f100)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p
/protocol/identify/id.go:411 +0x58b
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*I
DService).consumeMessage(0xc420090c00, 0xc434976e10, 0x16fc000, 0xc43603f100)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p
/protocol/identify/id.go:205 +0x124
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*I
DService).ResponseHandler(0xc420090c00, 0x16fce60, 0xc43b65d180)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p
/protocol/identify/id.go:152 +0x24e
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify.(*I
DService).IdentifyConn(0xc420090c00, 0x16fc000, 0xc43603f100)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/protocol/identify/id.go:112 +0x7c9
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic.(*BasicHost).newConnHandler(0xc4207fe680, 0x16fc000, 0xc43603f100)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic/basic_host.go:227 +0xa5
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic.(*BasicHost).(github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic.newConnHandler)-fm(0x16fc000, 0xc43603f100)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmNh1kGFFdsPu79KNSaL4NUKUPb4Eiz4KHdMtFY6664RDp/go-libp2p/p2p/host/basic/basic_host.go:174 +0x3e
github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm.(*Network).SetConnHandler.func1(0xc43603f100)
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm/swarm_net.go:160 +0x3b
created by github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm.(*Swarm).SetConnHandler.func2
        /ext-go/1/src/github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmSwZMWwFZSUpe5muU2xgTUwppH24KfMwdPXiwbEp2c6G5/go-libp2p-swarm/swarm.go:260 +0x67

```

**Comment by placer14** [comment] 2018-11-07 16:08
@jlopp The crash was due to bad network state which should no longer be occurring. (Note the timestamp of that log.) We still need to make the server more resilient to IPFS crashes though. Thanks sharing your report.

**Comment by placer14** [comment] 2018-12-06 22:11
No new reports in some time. Closing.

**Closed by placer14** 2018-12-06 22:11 UTC
Labels: multiwallet, ❗❗❗high priority
