### ISSUE TITLE
Prevent Follow/Unfollow Spam

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#668] opened 2017-09-07 14:24 UTC
It's very easy to spam notifications by following/unfollowing someone repeatedly. 

I don't think we should generate a follow notification if the same person has followed you within the last 24 hours.

**Comment by cpacia** [comment] 2017-09-07 19:33
duplicate of #620

**Closed by cpacia** 2017-09-07 19:33 UTC
Labels: duplicate
