### ISSUE TITLE
Double dispute notification for a mod when a dispute is first opened

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#544] opened 2017-06-16 22:18 UTC
Observed:
When a dispute is first opened, the moderator gets both a disputeOpen and disputeUpdate notification:

![image](https://user-images.githubusercontent.com/794517/27246468-abd077f2-52a6-11e7-96f0-d1717f19227e.png)

Expected:
Only the disputeOpen notification comes when the dispute is first opened. disputeUpdate would come if and when the dispute is subsequently updated.

**Comment by rmisio** [comment] 2017-06-23 19:13
@cpacia What would trigger a disputeUpdate notification and which parties would receive it?

**Comment by cpacia** [comment] 2017-06-26 14:24
Update is the other party automatically sending his copy of the dispute to the vendor. 

Closing because this is the expected behavior.

**Closed by cpacia** 2017-06-26 14:24 UTC
