### ISSUE TITLE
Buyer should validate escrowTimeoutHours upon a purchase

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#974] opened 2018-06-15 17:36 UTC
Since we're not displaying the escrowTimeoutHours in a listing anywhere at any point, during a purchase attempt the buyer should validate the value is what the server sets it to to ensure it wasn't set to some unexpected value.

**Comment by placer14** [comment] 2018-06-25 21:32
Closing as duplicate of #984.

**Closed by placer14** 2018-06-25 21:32 UTC
Labels: changes requested, invalid
