### ISSUE TITLE
When there are no ETH transactions, the `/wallet/transactions/` response does not match the response of other coins

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1756] opened 2019-10-02 22:24 UTC
for example:

`http://localhost:4002/wallet/transactions/TBTC?limit=25`

returns:

```
{
    "count": 0
}
```

whereas `http://localhost:4002/wallet/transactions/TETH?limit=25` returns:

```
{
    "success": false,
    "reason": "etherscan server: No transactions found"
}
```

Can the ETH response be consistent with the other coins and return `{ "count": 0 }`

**Comment by drwasho** [comment] 2019-10-03 05:20
Duplicate of #1754

**Closed by drwasho** 2019-10-03 05:20 UTC
Labels: ethereum
