### ISSUE TITLE
Some nodes are publishing the same root hash corresponding to the "empty" OB object

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#465] opened 2017-03-17 10:47 UTC
The Duo scraper has on record 12 guids publishing the root hash [`QmZbBumNEK9WjDRQmtjEsL138zRRqC2S6vTsyt9yVVxXCz`](http://gateway.ob1.io/ipfs/QmZbBumNEK9WjDRQmtjEsL138zRRqC2S6vTsyt9yVVxXCz).

<img width="490" alt="screen shot 2017-03-17 at 10 46 57" src="https://cloud.githubusercontent.com/assets/731743/24040004/10e409e6-0aff-11e7-8be5-b4bf41cc395e.png">

In particular this is affecting the Duo echo node. A particularly strange thing is that the IPNS sequence numbers are increasing but the root hash stays the same. To me this indicates a bug with `openbazaar-go`.

<img width="860" alt="screen shot 2017-03-17 at 10 46 16" src="https://cloud.githubusercontent.com/assets/731743/24039973/fb7acc02-0afe-11e7-8339-7e85231c73e7.png">

**Comment by jackkleeman** [comment] 2017-03-17 13:23
@cpacia I think this is what you were seeing too

**Comment by cpacia** [comment] 2017-03-17 14:48
I don't know what the cause is but why would other nodes publishing an empty object cause duo to do it?

**Comment by JustinDrake** [comment] 2017-03-17 15:18
I'm not claiming causation, just correlation.

**Comment by cpacia** [comment] 2017-03-17 15:54
I'm pretty sure I didn't make any changes to anything ipfs relates so I'm not sure what would kick this off. When I rebase to 0.4.7 we'll have to see if it's still happening.

**Comment by cpacia** [comment] 2017-04-21 03:03
Closing because we're on ipfs 0.4.8 now and I haven't seen the issue since 0.4.6.

**Closed by cpacia** 2017-04-21 03:03 UTC
Labels: bug
