### ISSUE TITLE
GET /wallet/transactions returning bad balances

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1706] opened 2019-09-18 02:55 UTC
As reported in https://github.com/OB1Company/native-bazaar/issues/1336, when making any transactions, they are not properly reported by `GET /wallet/transactions/:coinType`.

**Comment by cpacia** [comment] 2019-10-01 16:54
Closing this. The amount being reported by the tx api is the amount sent plus the fee. In other words, the amount is the total amount that left the wallet. This is the expected behavior. The users were confused because the amount recorded was higher than what they thought they sent, but it's because they weren't considering the fee. If you add the amount sent plus the fee it adds up exactly to the amount shown in the wallet.

**Closed by cpacia** 2019-10-01 16:54 UTC
Labels: bug, ethereum, external, needs validation
