### ISSUE TITLE
Double negative refund value

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1812] opened 2019-10-22 20:33 UTC
I canceled an offline order and it resulted in a `refundAddressTransaction` with the hyphen included twice within `bigValue`:

```    
"refundAddressTransaction": {
        "txid": "56d8ffcbcbccd428c5248062d3b595724a44e32722650dc6645702fbed869cb7",
        "value": 0,
        "confirmations": 102,
        "height": 1723654,
        "timestamp": "2019-10-22T15:29:15.683059Z",
        "currency": {
            "code": "LTC",
            "divisibility": 8
        },
        "bigValue": "--331462"
    }
```

**Comment by placer14** [comment] 2019-10-22 20:41
Maybe related to #1499?

**Comment by placer14** [comment] 2019-10-22 20:42
Oh, I see. Not double as in size, but double as in two hyphens. Subtle difference.

**Comment by rmisio** [comment] 2019-10-22 20:51
> Oh, I see. Not double as in size, but double as in two hyphens. Subtle difference.

Yeah sorry, I was a bit ambiguous there.

**Comment by drwasho** [comment] 2019-10-23 01:10
Closing since it's a duplicate of https://github.com/OpenBazaar/openbazaar-go/issues/1803

**Closed by drwasho** 2019-10-23 01:10 UTC
Labels: :rocket: :no_entry_sign:, bug, ethereum
