### ISSUE TITLE
Validations should be done outside of the JSON API handlers

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#358] opened 2017-02-08 17:02 UTC
This is not always respected, e.g. 

```
	if len(chat.Subject) > 500 {
		ErrorResponse(w, http.StatusBadRequest, "Subject line is too long")
		return
	}
	if len(chat.Message) > 20000 {
		ErrorResponse(w, http.StatusBadRequest, "Message is too long")
		return
	}
```

**Comment by placer14** [comment] 2018-06-29 15:42
Batch with #187

**Comment by placer14** [comment] 2019-01-14 14:07
Duplicate of https://github.com/OpenBazaar/openbazaar-go/issues/1397

**Closed by placer14** 2019-01-14 14:07 UTC
Labels: enhancement, ❗low priority
