### ISSUE TITLE
Have coinType be used consistently across the listing and listing index apis

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1768] opened 2019-10-09 19:53 UTC
For crypto currency listings, the listing API refers to the coin being traded as `coinType`, but in the listing index, it comes back as `cryptoCurrencyCode`.

Can the listing index use `coinType` to be consistent with the Listing api?

**Comment by placer14** [comment] 2019-10-09 20:13
Absolutely. I'll get this fixed in the next merge.

**Comment by placer14** [comment] 2019-10-14 13:36
Dupe of #1727.

**Closed by placer14** 2019-10-14 13:36 UTC
Labels: ethereum
