### ISSUE TITLE
POST repo.PurchaseData item quantity is not a string

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1790] opened 2019-10-16 14:25 UTC
Need to convert to a string from a uint64.

**Comment by drwasho** [comment] 2019-10-22 04:26
Not sure if it's related but I made a purchase with this as the payload:

![image](https://user-images.githubusercontent.com/3887694/67259125-99fab080-f4d7-11e9-82b1-dfe58e4a2ffb.png)

After making a `POST /ob/orderspend` call to fund the order, the order details changed to `AWAITING_FULFILLMENT` as expected, but the quantity value in the `this.contract.buyerOrder` zero:

![image](https://user-images.githubusercontent.com/3887694/67259117-8e0eee80-f4d7-11e9-9e3c-cd0b055c7096.png)

Also there are 3 keys for quantity...

**Comment by drwasho** [comment] 2019-10-28 22:48
Duplicate of #1814 and fixed in #1828

**Closed** 2019-10-28 22:48 UTC
Labels: :rocket: :no_entry_sign:, ethereum
