### ISSUE TITLE
Review validateListing() – round 2

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#170] opened 2016-10-22 20:22 UTC
These comments are in addition to pull-request #169. My suggest is to merge the pull-request first, and then address these issues.
1. Missing check for `len(listing.Item.Tags) == 0`
2. Missing check for `len(listing.Item.Categories) == 0`
3. Suggest replacing `MaxTags` and `MaxCategories` by `MaxListItems`
4. `AcceptedCurrency` is not validated on save
5. Depending on use case, inadequate `filename` validation. Most OS will barf on many Unicode characters.
6. If `description` is intended to contain HTML, then sanitation is missing.
7. Depending on use case, inadequate `slug` validation. Why only reject spaces? What about other whitespace (such as &emsp;)? What about other funky unicode characters?
8. Suggest maching currency codes against the regex `$[A-Z]{3}^`
9. Should `vendorID` be checked?
10. Missing `tax.Percentage > 100` check
11. Missing check for max number of tax regions
12. Missing check for max number of moderators
13. Missing check for max number of variants
14. Missing check for max number of regions

**Comment by cpacia** [comment] 2016-10-22 20:39
1 & 2: I think we weren't planning on forcing someone to use those fields.

3. Since tags go in the dht, 30 is probably too many. I'm also hard pressed t see someone using 30 categories for a single item.

4. It's added automatically by the server so it doesn't need to be validated.

6. All saved data need to be run through a sanitizer. That hasnt been written yet.

7. Possibly. We are likely going to have the server generate the slug in most cases. I'm not sure it would break anything other than aesthetics if they put other characters in.

9. This is automatically added by the server when the listing is saved so it wont be invalid. It should probably be checked in the purchase function in orders.go

**Comment by JustinDrake** [comment] 2016-10-22 20:56
I don't understand the argument "it is added automatically by the server, so does not need validation". What happens if a node requests a listing from a malicious node? That malicious node can have a custom server which could feed arbitrary data. If for example `AcceptedCurrency` is not validated and naively passed to the frontend, that gives an attacker wiggle room to be nefarious. Am I missing something here?

If I understood correctly, the point of slugs is to make `ob://` links readable, e.g. `ob://@openbazaar/cool-blue-tshirt`. As such, they effectively become URIs, and the intent is for them to be shared as such (e.g. on social media). Slugs should then be valid URI fragments.

**Comment by cpacia** [comment] 2016-10-24 16:36
The issue is IPFS data is current served directly from the ipfs part of the code. IPFS doesn't know, "This is a listing, I need to validate it first before serving", "This is a profile", etc. 

The server does validate listings before purchasing so it's not possible for someone to lose money on a malformatted listing. Do you have other attacks in mind?

**Comment by JustinDrake** [comment] 2016-10-24 20:42
Before a listing is purchased that listing needs to be displayed on screen. For that, `openbazaar-desktop` calls `GETListing` which itself calls `GetListingFromSlug` and responds with a `contract`. I find two things surprising in [`GetListingFromSlug`](https://github.com/OpenBazaar/openbazaar-go/blob/cb25fd87c35327cdc483241bdc8378daa0bb8b5d/core/listings.go#L472):

1. It does not take a `peerId` contrary to the documentation https://cpacia.github.io
2. It does not call `validateListing`, which means a malformed `contract` could be fed to `openbazaar-desktop`.

Am I missing something?

**Comment by cpacia** [comment] 2016-10-24 20:47
Looks like I have to update that documentation but the `GET ob/listing` API call only returns one's own listings. It does that so that it can append inventory and listing status (active, draft, etc) to the return.

currently the client is fetching listings for other nodes using ```https://localhost:8080/ipns/{peerId}/listings/{slug}```

**Comment by JustinDrake** [comment] 2016-10-24 21:03
Ok. When a listing is fetched with `https://localhost:8080/ipns/{peerId}/listing/{slug}` (I'm assuming you meant `/listing` singular, not `/listings` plural) why isn't `validateListing` called?

**Closed** 2017-03-09 15:23 UTC
Labels: discussion
