### ISSUE TITLE
Please provide socket to moderator if an order under active dispute is refunded.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#551] opened 2017-06-22 17:24 UTC
With the socket, if the order is refunded while the mod is looking at the case in the UI, the UI can be updated so the Resolve dispute button is hidden and the UI could reflect that the case was closed.

The assumption is that the case should be closed if the order is refunded. That doesn't look like it's happening which is related to:
https://github.com/OpenBazaar/openbazaar-go/issues/550

**Comment by cpacia** [comment] 2017-06-26 19:12
The issue is the vendor can't just tell the moderator "I refunded the order, you can close it now" because he could just lie. Then the moderator cannot legitimately resolve the dispute in favor of the buyer.

**Closed** 2019-07-31 22:07 UTC
Labels: TODO, discussion
